# Setup
title:               Cosmotheisms
tagline:             'Code Odyssey'
description:         'Below are some helpful links to my code stuff'
url:                 https://thenathe.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              THENATHE
  url:               https://thenathe.linktr.ee
  email:             NA@NA.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
